version: '3.8'

services:
  db-master:
    image: mariadb:11.3
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
    volumes:
      - db-master-data:/var/lib/mysql
      - ./init-scripts/00-create-replica-user.sql:/docker-entrypoint-initdb.d/00-create-replica-user.sql
    command:
      - --server-id=1
      - --gtid-strict-mode=ON
      - --log-bin=binlog
      - --binlog-format=ROW

  db-slave1:
    image: mariadb:11.3
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
    volumes:
      - db-slave1-data:/var/lib/mysql
      - ./init-scripts/01-start-slave.sql:/docker-entrypoint-initdb.d/01-start-slave.sql
    command:
      - --server-id=2
      - --gtid-strict-mode=ON
      - --log-bin=binlog
      - --binlog-format=ROW
      - --read-only=ON

  db-slave2:
    image: mariadb:11.3
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
    volumes:
      - db-slave2-data:/var/lib/mysql
      - ./init-scripts/01-start-slave.sql:/docker-entrypoint-initdb.d/01-start-slave.sql
    command:
      - --server-id=3
      - --gtid-strict-mode=ON
      - --log-bin=binlog
      - --binlog-format=ROW
      - --read-only=ON

  proxysql:
    image: proxysql/proxysql:3.0.1
    ports:
      - "6033:6033"  # MySQL port (read/write traffic)
      - "6032:6032"  # Admin console
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf
    depends_on:
      - db-master
      - db-slave1
      - db-slave2

volumes:
  db-master-data:
  db-slave1-data:
  db-slave2-data:
